name: SynthPops Docs workflow
on:
  push:
    branches:
      - master

jobs:
  docs:
    runs-on: ubuntu-latest
    if: github.repository == 'InstituteforDiseaseModeling/synthpops'
    strategy:
      fail-fast: false
      max-parallel: 8
      matrix:
        python-version: ['3.7']
    name: Install and Generate Docs
    steps:
      - name: Set repo owner env variable
        shell: python
        run: print("::set-env name=GITHUB_OWNER::{}".format('${{github.repository}}'.split('/')[0]))
      - name: Set repo owner env variable
        shell: python
        run: print("::set-env name=GITHUB_OWNER::{}".format('${{github.repository}}'.split('/')[0]))
      - name: Set PYTHONPATH
        run: |
          mkdir -p $HOME/.cache/site-packages
          echo "::set-env name=PYTHONPATH::$HOME/.cache/site-packages"
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          path: synthpops
      - name: Checkout gh-pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages
      - uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Cache Packages
        id: cache-packages
        uses: actions/cache@v1
        with:
          path: ~/.cache/ # This path is specific to Ubuntu
          key: docs-packages-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('requirements.txt') }}--${{ hashFiles('docs/requirements.txt') }} # Look to see if there is a cache hit for the corresponding requirements file
          restore-keys: |
            docs-packages-${{ runner.os }}-${{ matrix.python-version }}- # Pip install first will make setup.py much faster and the cache will make pip install fast
      - name: Install SynthPops
        run: |
          pushd synthpops 
          python setup.py develop --install-dir ~/.cache/site-packages
          pip3 install -r docs/requirements.txt
          popd

      - name: Build Docs
        run: |
          pushd  synthpops/docs
          make html
          popd

          rm -rf gh-pages/*
          rsync -r synthpops/docs/_build/html/ gh-pages/
      - name: Commit Docs
        run: |
          pushd gh-pages
          if [ ! -z "$(git status --porcelain)" ]; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add --all .
            git commit -m "Update Docs"
            
            # Setup deploy key
            eval "$(ssh-agent -s)"
            ssh-add - <<< "${{ secrets.DOCS_DEPLOY_KEY }}"

            # Deploy
            remote_repo="git@github.com:${{ github.repository }}.git"
            git push "${remote_repo}" HEAD:gh-pages
          fi
          popd
