name: Synthpops CI workflow
on: [pull_request]

jobs:
  install_and_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 8
      matrix:
        python-version: [ '3.7' ]
    name: Install and test
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1
      - uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install synthpops
        run: python setup.py develop
      - name: Run tests
        working-directory: ./tests
        run: |
          pip install pytest
          pytest test_*.py --durations=0 # Run actual tests

      - name: Upload test results
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: test_results
          path: tests/test-results.xml